"use client";

import { Badge } from "@wraps/ui/components/ui/badge";
import { Button } from "@wraps/ui/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@wraps/ui/components/ui/card";
import {
  ArrowLeft,
  Check,
  Clock,
  Database,
  GitFork,
  Globe,
  Key,
  RefreshCw,
  Server,
  Shield,
  Zap,
} from "lucide-react";
import Link from "next/link";
import { CLICommand } from "@/components/docs/cli-command";
import { DocsLayout } from "@/components/docs-layout";
import {
  CodeBlock,
  CodeBlockBody,
  CodeBlockContent,
  CodeBlockCopyButton,
  CodeBlockFilename,
  CodeBlockFiles,
  CodeBlockHeader,
  CodeBlockItem,
} from "@/components/ui/shadcn-io/code-block";

const deployExample = `# Pass all required values as flags (non-interactive):
pnpm selfhost:deploy \\
  --database-url "postgres://user:pass@your-db.neon.tech/wraps" \\
  --license-key "wraps_lic_..." \\
  --yes

# Or run without flags — the script will prompt you:
pnpm selfhost:deploy`;

const envSelfhostExample = `# Created automatically by pnpm selfhost:deploy
DATABASE_URL=postgres://user:pass@your-db.neon.tech/wraps
BETTER_AUTH_SECRET=<auto-generated>
UNSUBSCRIBE_SECRET=<auto-generated>
LICENSE_KEY=wraps_lic_...

# Populated after SST deploy completes:
NEXT_PUBLIC_APP_URL=https://dashboard.yourdomain.com
WRAPS_API_URL=https://abc123.lambda-url.us-east-1.on.aws
BETTER_AUTH_URL=https://dashboard.yourdomain.com

# Populated if email infrastructure was found:
WRAPS_EMAIL_ROLE_ARN=arn:aws:iam::123456789012:role/wraps-email-role
AUTH_EMAIL_CONFIGURATION_SET=wraps-email-events
AUTH_EMAIL_FROM=noreply@yourdomain.com`;

const vercelEnvExample = `# From .env.selfhost — copy these into Vercel project settings:
DATABASE_URL=postgres://user:pass@your-db.neon.tech/wraps
NEXT_PUBLIC_APP_URL=https://dashboard.yourdomain.com
NEXT_PUBLIC_API_URL=https://abc123.lambda-url.us-east-1.on.aws
CORS_ORIGIN=https://dashboard.yourdomain.com
BETTER_AUTH_SECRET=<from .env.selfhost>
UNSUBSCRIBE_SECRET=<from .env.selfhost>
WRAPS_LICENSE_KEY=wraps_lic_...
AWS_BACKEND_ACCOUNT_ID=123456789012

# Added after Step 5 (Vercel OIDC):
AWS_ROLE_ARN=arn:aws:iam::123456789012:role/wraps-vercel-backend-role`;

const oidcTrustPolicyExample = `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::YOUR_ACCOUNT_ID:oidc-provider/oidc.vercel.com/YOUR_TEAM_ID"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.vercel.com/YOUR_TEAM_ID:aud": "sts.amazonaws.com"
        }
      }
    }
  ]
}`;

const oidcPermissionsPolicyExample = `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "sts:AssumeRole",
      "Resource": "arn:aws:iam::YOUR_ACCOUNT_ID:role/wraps-console-access-role"
    }
  ]
}`;

const githubOidcTrustPolicyExample = `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::YOUR_ACCOUNT_ID:oidc-provider/token.actions.githubusercontent.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
        },
        "StringLike": {
          "token.actions.githubusercontent.com:sub": "repo:YOUR_GITHUB_ORG/wraps:*"
        }
      }
    }
  ]
}`;

const upgradeExample = `# Manual upgrade from your fork:
pnpm selfhost:upgrade

# Runs SST deploy + database migrations automatically`;

export default function SelfHostedPageContent() {
  return (
    <DocsLayout>
      {/* Back Link */}
      <div className="mb-8">
        <Button asChild className="gap-2" variant="ghost">
          <Link href="/docs/guides">
            <ArrowLeft className="h-4 w-4" />
            Back to Guides
          </Link>
        </Button>
      </div>

      {/* Page Header */}
      <div className="mb-12">
        <Badge className="mb-4" variant="outline">
          Guide
        </Badge>
        <h1 className="mb-4 font-bold text-4xl tracking-tight">
          Self-Hosted Deployment
        </h1>
        <p className="text-lg text-muted-foreground">
          Deploy the full Wraps control plane to your own AWS account. Your API,
          your dashboard, your database — everything in your infrastructure with
          no Wraps servers in the critical path.
        </p>
        <div className="mt-4 flex items-center gap-4 text-muted-foreground text-sm">
          <span className="flex items-center gap-1">
            <Clock className="h-4 w-4" />
            30–45 min
          </span>
        </div>
      </div>

      {/* Overview */}
      <section className="mb-12">
        <h2 className="mb-4 font-bold text-2xl">Overview</h2>
        <p className="mb-4 text-muted-foreground">
          Self-hosting deploys the Wraps control plane as an AWS Lambda function
          backed by your own Postgres database, using SST v3 for infrastructure
          management. You fork the Wraps repository, configure a handful of
          secrets, and run a single command. Your team's dashboard runs on Vercel
          and connects to the Lambda directly — no Wraps SaaS in the loop.
        </p>
        <Card>
          <CardContent className="p-6">
            <ul className="space-y-3">
              <li className="flex items-start gap-3">
                <GitFork className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                <div>
                  <span className="font-medium">Fork-based deployment</span>
                  <p className="text-muted-foreground text-sm">
                    Fork the Wraps repo, run{" "}
                    <code className="rounded bg-muted px-1.5 py-0.5">
                      pnpm selfhost:deploy
                    </code>
                    , and receive upstream updates on your schedule via a weekly
                    sync PR
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <Server className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                <div>
                  <span className="font-medium">
                    Control plane API on Lambda
                  </span>
                  <p className="text-muted-foreground text-sm">
                    Deployed into your AWS account via SST — you own the
                    function, logs, and billing
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <Database className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                <div>
                  <span className="font-medium">Your Postgres database</span>
                  <p className="text-muted-foreground text-sm">
                    Bring any Postgres-compatible DB (Neon, Supabase, Railway,
                    self-hosted)
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <Globe className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                <div>
                  <span className="font-medium">Dashboard on Vercel</span>
                  <p className="text-muted-foreground text-sm">
                    Deploy{" "}
                    <code className="rounded bg-muted px-1.5 py-0.5">
                      apps/web
                    </code>{" "}
                    from your fork to your own Vercel project
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <Shield className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                <div>
                  <span className="font-medium">Zero stored credentials</span>
                  <p className="text-muted-foreground text-sm">
                    Dashboard authenticates to AWS via Vercel OIDC federation —
                    no static keys
                  </p>
                </div>
              </li>
            </ul>
          </CardContent>
        </Card>
      </section>

      {/* Prerequisites */}
      <section className="mb-12">
        <h2 className="mb-4 font-bold text-2xl">Prerequisites</h2>
        <Card>
          <CardContent className="p-6">
            <ul className="space-y-3 text-muted-foreground">
              <li className="flex items-center gap-3">
                <Check className="h-5 w-5 shrink-0 text-green-500" />
                <span>
                  Node.js 20+ and pnpm 10+ installed locally
                </span>
              </li>
              <li className="flex items-center gap-3">
                <Check className="h-5 w-5 shrink-0 text-green-500" />
                <span>
                  AWS CLI configured with credentials that have IAM, Lambda,
                  S3, CloudFormation, and SSM permissions
                </span>
              </li>
              <li className="flex items-center gap-3">
                <Check className="h-5 w-5 shrink-0 text-green-500" />
                <span>
                  Postgres database connection string (Neon, Supabase, Railway,
                  or self-hosted)
                </span>
              </li>
              <li className="flex items-center gap-3">
                <Check className="h-5 w-5 shrink-0 text-green-500" />
                <span>
                  Wraps enterprise license key — contact{" "}
                  <Link
                    className="text-primary underline underline-offset-2"
                    href="/contact"
                  >
                    wraps.dev/contact
                  </Link>{" "}
                  to get one
                </span>
              </li>
              <li className="flex items-center gap-3">
                <Check className="h-5 w-5 shrink-0 text-green-500" />
                <span>
                  Vercel account and a project to deploy the dashboard
                </span>
              </li>
              <li className="flex items-center gap-3">
                <Check className="h-5 w-5 shrink-0 text-green-500" />
                <span>
                  GitHub account for forking the repository
                </span>
              </li>
            </ul>
          </CardContent>
        </Card>
      </section>

      {/* Step 1 */}
      <section className="mb-12">
        <h2 className="mb-4 flex items-center gap-2 font-bold text-2xl">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm font-bold">
            1
          </div>
          Fork the Repository
        </h2>
        <p className="mb-4 text-muted-foreground">
          The self-hosted deployment scripts live in the Wraps monorepo. Fork it
          so you can receive upstream updates on your own schedule.
        </p>
        <ol className="mb-4 list-decimal space-y-4 pl-6 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">Fork on GitHub</span>{" "}
            — go to{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">
              github.com/wraps-team/wraps
            </code>{" "}
            and click Fork. Keep the default branch name{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">main</code>.
          </li>
          <li>
            <span className="font-medium text-foreground">
              Clone your fork and install
            </span>
            :
            <div className="mt-2">
              <CodeBlock
                className="h-auto"
                data={[
                  {
                    language: "bash",
                    filename: "Terminal",
                    code: `git clone https://github.com/YOUR_ORG/wraps.git
cd wraps
pnpm install`,
                  },
                ]}
                defaultValue="bash"
              >
                <CodeBlockHeader>
                  <CodeBlockFiles>
                    {(item) => (
                      <CodeBlockFilename key={item.language} value={item.language}>
                        {item.filename}
                      </CodeBlockFilename>
                    )}
                  </CodeBlockFiles>
                  <CodeBlockCopyButton />
                </CodeBlockHeader>
                <CodeBlockBody>
                  {(item) => (
                    <CodeBlockItem
                      key={item.language}
                      lineNumbers={false}
                      value={item.language}
                    >
                      <CodeBlockContent language={item.language}>
                        {item.code}
                      </CodeBlockContent>
                    </CodeBlockItem>
                  )}
                </CodeBlockBody>
              </CodeBlock>
            </div>
          </li>
        </ol>
      </section>

      {/* Step 2 */}
      <section className="mb-12">
        <h2 className="mb-4 flex items-center gap-2 font-bold text-2xl">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm font-bold">
            2
          </div>
          Deploy the Control Plane
        </h2>
        <p className="mb-4 text-muted-foreground">
          Run the deploy script from the root of your fork. It provisions all
          AWS infrastructure via SST, runs database migrations, and writes an{" "}
          <code className="rounded bg-muted px-1.5 py-0.5">.env.selfhost</code>{" "}
          file with the outputs.
        </p>
        <div className="mb-4">
          <CodeBlock
            className="h-auto"
            data={[
              {
                language: "bash",
                filename: "Terminal",
                code: deployExample,
              },
            ]}
            defaultValue="bash"
          >
            <CodeBlockHeader>
              <CodeBlockFiles>
                {(item) => (
                  <CodeBlockFilename key={item.language} value={item.language}>
                    {item.filename}
                  </CodeBlockFilename>
                )}
              </CodeBlockFiles>
              <CodeBlockCopyButton />
            </CodeBlockHeader>
            <CodeBlockBody>
              {(item) => (
                <CodeBlockItem
                  key={item.language}
                  lineNumbers={false}
                  value={item.language}
                >
                  <CodeBlockContent language={item.language}>
                    {item.code}
                  </CodeBlockContent>
                </CodeBlockItem>
              )}
            </CodeBlockBody>
          </CodeBlock>
        </div>
        <p className="mb-4 text-muted-foreground">The script will:</p>
        <ol className="mb-4 list-decimal space-y-2 pl-6 text-muted-foreground">
          <li>Check your AWS credentials</li>
          <li>Prompt for any missing values (database URL, license key, region)</li>
          <li>
            Write{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">.env.selfhost</code>{" "}
            with auto-generated secrets
          </li>
          <li>Run SST bootstrap and deploy the Lambda + supporting resources</li>
          <li>Run Drizzle migrations against your Postgres database</li>
          <li>
            Append the Lambda URL, app URL, and any email variables to{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">.env.selfhost</code>
          </li>
        </ol>
        <p className="mb-4 text-muted-foreground">
          After the deploy completes, your{" "}
          <code className="rounded bg-muted px-1.5 py-0.5">.env.selfhost</code>{" "}
          will look like this:
        </p>
        <CodeBlock
          className="mb-4 h-auto"
          data={[
            {
              language: "bash",
              filename: ".env.selfhost",
              code: envSelfhostExample,
            },
          ]}
          defaultValue="bash"
        >
          <CodeBlockHeader>
            <CodeBlockFiles>
              {(item) => (
                <CodeBlockFilename key={item.language} value={item.language}>
                  {item.filename}
                </CodeBlockFilename>
              )}
            </CodeBlockFiles>
            <CodeBlockCopyButton />
          </CodeBlockHeader>
          <CodeBlockBody>
            {(item) => (
              <CodeBlockItem
                key={item.language}
                lineNumbers={false}
                value={item.language}
              >
                <CodeBlockContent language={item.language}>
                  {item.code}
                </CodeBlockContent>
              </CodeBlockItem>
            )}
          </CodeBlockBody>
        </CodeBlock>
        <div className="rounded-lg border-primary border-l-4 bg-primary/10 p-4">
          <p className="font-medium text-sm">Optional flags</p>
          <p className="mt-2 text-muted-foreground text-sm">
            Pass{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">--web-domain</code>{" "}
            to set a custom domain for the dashboard (e.g.{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">
              dashboard.yourdomain.com
            </code>
            ) and{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">
              --ai-gateway-api-key
            </code>{" "}
            to enable AI email generation features. Both can be added later by
            re-running{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">
              pnpm selfhost:upgrade
            </code>
            .
          </p>
        </div>
      </section>

      {/* Step 3 */}
      <section className="mb-12">
        <h2 className="mb-4 flex items-center gap-2 font-bold text-2xl">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm font-bold">
            3
          </div>
          Deploy Email Infrastructure
        </h2>
        <p className="mb-4 text-muted-foreground">
          Initialise email sending with AWS SES. This creates IAM roles,
          configures SES, and sets up event processing for open and click
          tracking.
        </p>
        <div className="mb-4">
          <CLICommand command="wraps email init" />
        </div>
        <p className="text-muted-foreground text-sm">
          If you only need SMS, skip this step and run{" "}
          <code className="rounded bg-muted px-1.5 py-0.5">wraps sms init</code>{" "}
          instead.
        </p>
      </section>

      {/* Step 4 */}
      <section className="mb-12">
        <h2 className="mb-4 flex items-center gap-2 font-bold text-2xl">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm font-bold">
            4
          </div>
          Deploy the Dashboard to Vercel
        </h2>
        <p className="mb-4 text-muted-foreground">
          The Wraps dashboard lives in{" "}
          <code className="rounded bg-muted px-1.5 py-0.5">apps/web</code> in
          your fork. Connect it to a Vercel project and add the environment
          variables from your{" "}
          <code className="rounded bg-muted px-1.5 py-0.5">.env.selfhost</code>{" "}
          file.
        </p>
        <ol className="mb-4 list-decimal space-y-4 pl-6 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">
              Create a Vercel project
            </span>{" "}
            — connect your fork in Vercel and set the root directory to{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">apps/web</code>.
          </li>
          <li>
            <span className="font-medium text-foreground">
              Add environment variables
            </span>{" "}
            — in Vercel → Project Settings → Environment Variables, add the
            following (scoped to Production):
            <div className="mt-3">
              <CodeBlock
                className="h-auto"
                data={[
                  {
                    language: "bash",
                    filename: "Vercel env vars",
                    code: vercelEnvExample,
                  },
                ]}
                defaultValue="bash"
              >
                <CodeBlockHeader>
                  <CodeBlockFiles>
                    {(item) => (
                      <CodeBlockFilename
                        key={item.language}
                        value={item.language}
                      >
                        {item.filename}
                      </CodeBlockFilename>
                    )}
                  </CodeBlockFiles>
                  <CodeBlockCopyButton />
                </CodeBlockHeader>
                <CodeBlockBody>
                  {(item) => (
                    <CodeBlockItem
                      key={item.language}
                      lineNumbers={false}
                      value={item.language}
                    >
                      <CodeBlockContent language={item.language}>
                        {item.code}
                      </CodeBlockContent>
                    </CodeBlockItem>
                  )}
                </CodeBlockBody>
              </CodeBlock>
            </div>
          </li>
          <li>
            <span className="font-medium text-foreground">
              Trigger a deployment
            </span>{" "}
            — the dashboard will build successfully but cannot call AWS until
            you complete Step 5.
          </li>
        </ol>
      </section>

      {/* Step 5 */}
      <section className="mb-12">
        <h2 className="mb-4 flex items-center gap-2 font-bold text-2xl">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm font-bold">
            5
          </div>
          Set Up Vercel OIDC Authentication
        </h2>
        <p className="mb-4 text-muted-foreground">
          The dashboard reads AWS resources (SES stats, CloudWatch, DynamoDB)
          without any stored credentials. It uses Vercel OIDC federation to
          obtain short-lived AWS tokens automatically.
        </p>
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Step 5a — Get your Vercel OIDC provider URL
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="mb-3 text-muted-foreground text-sm">
              In Vercel: go to your team's{" "}
              <span className="font-medium text-foreground">
                Settings → Cloud → Configure AWS
              </span>
              . Copy the OIDC provider URL — it looks like{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                https://oidc.vercel.com/your-team-id
              </code>
              .
            </p>
          </CardContent>
        </Card>
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Step 5b — Add an OIDC identity provider in AWS
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="mb-3 text-muted-foreground text-sm">
              In the AWS Console, go to{" "}
              <span className="font-medium text-foreground">
                IAM → Identity providers → Add provider
              </span>
              :
            </p>
            <ul className="space-y-1 text-muted-foreground text-sm">
              <li>
                <span className="font-medium text-foreground">
                  Provider type:
                </span>{" "}
                OpenID Connect
              </li>
              <li>
                <span className="font-medium text-foreground">
                  Provider URL:
                </span>{" "}
                paste your Vercel OIDC URL from 5a
              </li>
              <li>
                <span className="font-medium text-foreground">Audience:</span>{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">
                  sts.amazonaws.com
                </code>
              </li>
            </ul>
          </CardContent>
        </Card>
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Step 5c — Create an IAM role that trusts the OIDC provider
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="mb-3 text-muted-foreground text-sm">
              Create a new IAM role named{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                wraps-vercel-backend-role
              </code>{" "}
              (or similar) with two distinct policies:
            </p>
            <p className="mb-2 font-medium text-foreground text-sm">
              Trust policy (who can assume this role):
            </p>
            <p className="mb-2 text-muted-foreground text-sm">
              Replace{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                YOUR_ACCOUNT_ID
              </code>{" "}
              and{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                YOUR_TEAM_ID
              </code>{" "}
              with your AWS account ID and Vercel team ID from Step 5a:
            </p>
            <CodeBlock
              className="mb-4 h-auto"
              data={[
                {
                  language: "json",
                  filename: "trust-policy.json",
                  code: oidcTrustPolicyExample,
                },
              ]}
              defaultValue="json"
            >
              <CodeBlockHeader>
                <CodeBlockFiles>
                  {(item) => (
                    <CodeBlockFilename
                      key={item.language}
                      value={item.language}
                    >
                      {item.filename}
                    </CodeBlockFilename>
                  )}
                </CodeBlockFiles>
                <CodeBlockCopyButton />
              </CodeBlockHeader>
              <CodeBlockBody>
                {(item) => (
                  <CodeBlockItem
                    key={item.language}
                    lineNumbers={false}
                    value={item.language}
                  >
                    <CodeBlockContent language={item.language}>
                      {item.code}
                    </CodeBlockContent>
                  </CodeBlockItem>
                )}
              </CodeBlockBody>
            </CodeBlock>
            <p className="mb-2 font-medium text-foreground text-sm">
              Permissions policy (what this role can do):
            </p>
            <p className="mb-2 text-muted-foreground text-sm">
              This allows the Vercel backend role to chain-assume{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                wraps-console-access-role
              </code>
              , which is created automatically in Step 6 when you run{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                wraps selfhost connect
              </code>
              :
            </p>
            <CodeBlock
              className="mb-4 h-auto"
              data={[
                {
                  language: "json",
                  filename: "permissions-policy.json",
                  code: oidcPermissionsPolicyExample,
                },
              ]}
              defaultValue="json"
            >
              <CodeBlockHeader>
                <CodeBlockFiles>
                  {(item) => (
                    <CodeBlockFilename
                      key={item.language}
                      value={item.language}
                    >
                      {item.filename}
                    </CodeBlockFilename>
                  )}
                </CodeBlockFiles>
                <CodeBlockCopyButton />
              </CodeBlockHeader>
              <CodeBlockBody>
                {(item) => (
                  <CodeBlockItem
                    key={item.language}
                    lineNumbers={false}
                    value={item.language}
                  >
                    <CodeBlockContent language={item.language}>
                      {item.code}
                    </CodeBlockContent>
                  </CodeBlockItem>
                )}
              </CodeBlockBody>
            </CodeBlock>
            <p className="text-muted-foreground text-sm">
              Copy the ARN of the role you just created — it looks like{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                arn:aws:iam::YOUR_ACCOUNT_ID:role/wraps-vercel-backend-role
              </code>
              .
            </p>
          </CardContent>
        </Card>
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Step 5d — Set AWS_ROLE_ARN in Vercel
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="mb-3 text-muted-foreground text-sm">
              Add one more environment variable to your Vercel project using the
              role ARN from 5c, then redeploy:
            </p>
            <CodeBlock
              className="h-auto"
              data={[
                {
                  language: "bash",
                  filename: "Vercel env var",
                  code: `AWS_ROLE_ARN=arn:aws:iam::YOUR_ACCOUNT_ID:role/wraps-vercel-backend-role`,
                },
              ]}
              defaultValue="bash"
            >
              <CodeBlockHeader>
                <CodeBlockFiles>
                  {(item) => (
                    <CodeBlockFilename
                      key={item.language}
                      value={item.language}
                    >
                      {item.filename}
                    </CodeBlockFilename>
                  )}
                </CodeBlockFiles>
                <CodeBlockCopyButton />
              </CodeBlockHeader>
              <CodeBlockBody>
                {(item) => (
                  <CodeBlockItem
                    key={item.language}
                    lineNumbers={false}
                    value={item.language}
                  >
                    <CodeBlockContent language={item.language}>
                      {item.code}
                    </CodeBlockContent>
                  </CodeBlockItem>
                )}
              </CodeBlockBody>
            </CodeBlock>
          </CardContent>
        </Card>
      </section>

      {/* Step 6 */}
      <section className="mb-12">
        <h2 className="mb-4 flex items-center gap-2 font-bold text-2xl">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm font-bold">
            6
          </div>
          Create Your Account and Connect
        </h2>
        <p className="mb-4 text-muted-foreground">
          With the dashboard running, create your account, then authenticate the
          CLI against your instance and register the AWS connection.
        </p>
        <ol className="mb-6 list-decimal space-y-4 pl-6 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">
              Open your dashboard URL
            </span>{" "}
            and sign up with email and password.
          </li>
          <li>
            <span className="font-medium text-foreground">
              Create your organization
            </span>{" "}
            — you will be prompted during onboarding. The CLI requires an
            organization to exist before it can connect.
          </li>
          <li>
            <span className="font-medium text-foreground">Sign in the CLI</span>{" "}
            — reads your deployment metadata to find the dashboard URL, then
            opens a browser for device authorization against your own instance:
          </li>
        </ol>
        <div className="mb-4">
          <CLICommand command="wraps selfhost login" />
        </div>
        <div className="mb-6 rounded-lg border-primary border-l-4 bg-primary/10 p-4">
          <p className="font-medium text-sm">
            Why not{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">
              wraps auth login
            </code>
            ?
          </p>
          <p className="mt-2 text-muted-foreground text-sm">
            The standard login command authenticates against the Wraps SaaS
            platform.{" "}
            <code className="rounded bg-muted px-1.5 py-0.5">
              wraps selfhost login
            </code>{" "}
            reads your deployment metadata and authenticates against your own
            dashboard URL instead.
          </p>
        </div>
        <p className="mb-4 text-muted-foreground">
          Once signed in, register this AWS account with your self-hosted
          control plane. This creates the{" "}
          <code className="rounded bg-muted px-1.5 py-0.5">
            wraps-console-access-role
          </code>{" "}
          IAM role and enables event streaming from your email infrastructure
          to the dashboard:
        </p>
        <div className="mb-4">
          <CLICommand command="wraps selfhost connect" />
        </div>
        <div className="rounded-lg border-primary border-l-4 bg-primary/10 p-4">
          <p className="font-medium text-sm">Single-account deployments</p>
          <p className="mt-2 text-muted-foreground text-sm">
            The CLI automatically configures the trust policy to trust your own
            AWS account — not the Wraps SaaS platform account.
          </p>
        </div>
      </section>

      {/* Step 7 */}
      <section className="mb-12">
        <h2 className="mb-4 flex items-center gap-2 font-bold text-2xl">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm font-bold">
            7
          </div>
          Verify Your Deployment
        </h2>
        <p className="mb-4 text-muted-foreground">
          Check the health of your self-hosted control plane from the CLI:
        </p>
        <div className="mb-4">
          <CLICommand command="wraps selfhost status" />
        </div>
        <p className="mb-4 text-muted-foreground">
          A healthy deployment reports the API URL, Lambda ARN, deployed
          version, and database connectivity. Open your dashboard URL and
          confirm your connected AWS account and any email or SMS infrastructure
          are visible.
        </p>
        <div className="rounded-lg border-green-500 border-l-4 bg-green-500/10 p-4">
          <p className="font-medium text-sm">You are fully self-hosted</p>
          <p className="mt-2 text-muted-foreground text-sm">
            All API calls from the dashboard go directly to your Lambda. No
            Wraps SaaS servers are involved at runtime. Your license is verified
            offline — no phone-home required.
          </p>
        </div>
      </section>

      {/* Keeping Up to Date */}
      <section className="mb-12">
        <h2 className="mb-4 flex items-center gap-2 font-bold text-2xl">
          <RefreshCw className="h-6 w-6 text-primary" />
          Keeping Up to Date
        </h2>
        <p className="mb-6 text-muted-foreground">
          New Wraps releases include Lambda updates, database migrations, and
          dashboard improvements. Choose the upgrade path that fits your
          workflow.
        </p>

        <h3 className="mb-3 font-semibold text-lg">Manual upgrade</h3>
        <p className="mb-4 text-muted-foreground">
          Pull upstream changes into your fork, then run the upgrade script.
          It re-deploys the SST stack and runs any pending database migrations
          automatically.
        </p>
        <div className="mb-6">
          <CodeBlock
            className="h-auto"
            data={[
              {
                language: "bash",
                filename: "Terminal",
                code: upgradeExample,
              },
            ]}
            defaultValue="bash"
          >
            <CodeBlockHeader>
              <CodeBlockFiles>
                {(item) => (
                  <CodeBlockFilename key={item.language} value={item.language}>
                    {item.filename}
                  </CodeBlockFilename>
                )}
              </CodeBlockFiles>
              <CodeBlockCopyButton />
            </CodeBlockHeader>
            <CodeBlockBody>
              {(item) => (
                <CodeBlockItem
                  key={item.language}
                  lineNumbers={false}
                  value={item.language}
                >
                  <CodeBlockContent language={item.language}>
                    {item.code}
                  </CodeBlockContent>
                </CodeBlockItem>
              )}
            </CodeBlockBody>
          </CodeBlock>
        </div>
        <p className="mb-8 text-muted-foreground text-sm">
          After upgrading the Lambda, redeploy your Vercel dashboard project to
          pick up any frontend changes.
        </p>

        <h3 className="mb-3 font-semibold text-lg">
          Automated upgrades with GitHub Actions
        </h3>
        <p className="mb-4 text-muted-foreground">
          Your fork includes two pre-built workflows that handle the full
          update loop hands-free:
        </p>
        <div className="mb-6 grid gap-4 sm:grid-cols-2">
          <Card>
            <CardContent className="p-5">
              <p className="mb-1 font-medium text-sm">
                selfhost-sync.yml
              </p>
              <p className="text-muted-foreground text-sm">
                Runs every Monday. Fetches upstream{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">main</code>,
                opens a PR with a list of included commits. You review and merge
                when ready.
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-5">
              <p className="mb-1 font-medium text-sm">
                selfhost-deploy.yml
              </p>
              <p className="text-muted-foreground text-sm">
                Manual trigger only. Runs{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">
                  pnpm selfhost:upgrade
                </code>{" "}
                (or{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">deploy</code>{" "}
                for first-time) with OIDC credentials — no stored AWS keys.
              </p>
            </CardContent>
          </Card>
        </div>

        <p className="mb-6 text-muted-foreground">
          Follow these steps to enable them in your fork.
        </p>

        {/* GitHub Actions Setup */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Actions setup 1 — Enable workflows in your fork
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-muted-foreground text-sm">
              GitHub disables Actions on new forks by default. Go to your
              fork's{" "}
              <span className="font-medium text-foreground">
                Settings → Actions → General
              </span>{" "}
              and set "Allow all actions and reusable workflows", then save.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Actions setup 2 — Create an AWS OIDC identity provider for GitHub
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="mb-3 text-muted-foreground text-sm">
              In the AWS Console, go to{" "}
              <span className="font-medium text-foreground">
                IAM → Identity providers → Add provider
              </span>
              :
            </p>
            <ul className="mb-4 space-y-1 text-muted-foreground text-sm">
              <li>
                <span className="font-medium text-foreground">
                  Provider type:
                </span>{" "}
                OpenID Connect
              </li>
              <li>
                <span className="font-medium text-foreground">
                  Provider URL:
                </span>{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">
                  https://token.actions.githubusercontent.com
                </code>
              </li>
              <li>
                <span className="font-medium text-foreground">Audience:</span>{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">
                  sts.amazonaws.com
                </code>
              </li>
            </ul>
            <p className="mb-2 text-muted-foreground text-sm">
              Then create an IAM role named{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                wraps-github-deploy-role
              </code>{" "}
              (or similar) with the following trust policy. Replace{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                YOUR_ACCOUNT_ID
              </code>{" "}
              and{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">
                YOUR_GITHUB_ORG
              </code>{" "}
              with your AWS account ID and the GitHub username or org that owns
              your fork:
            </p>
            <CodeBlock
              className="mb-4 h-auto"
              data={[
                {
                  language: "json",
                  filename: "github-trust-policy.json",
                  code: githubOidcTrustPolicyExample,
                },
              ]}
              defaultValue="json"
            >
              <CodeBlockHeader>
                <CodeBlockFiles>
                  {(item) => (
                    <CodeBlockFilename
                      key={item.language}
                      value={item.language}
                    >
                      {item.filename}
                    </CodeBlockFilename>
                  )}
                </CodeBlockFiles>
                <CodeBlockCopyButton />
              </CodeBlockHeader>
              <CodeBlockBody>
                {(item) => (
                  <CodeBlockItem
                    key={item.language}
                    lineNumbers={false}
                    value={item.language}
                  >
                    <CodeBlockContent language={item.language}>
                      {item.code}
                    </CodeBlockContent>
                  </CodeBlockItem>
                )}
              </CodeBlockBody>
            </CodeBlock>
            <p className="text-muted-foreground text-sm">
              Attach an IAM permissions policy to this role with the
              permissions SST needs: Lambda, S3, CloudFormation, IAM, SSM
              Parameter Store, CloudWatch Logs, and STS. Copy the role ARN —
              you will need it in the next step.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Actions setup 3 — Configure secrets and variables
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="mb-4 text-muted-foreground text-sm">
              In your fork, go to{" "}
              <span className="font-medium text-foreground">
                Settings → Secrets and variables → Actions
              </span>{" "}
              and add the following:
            </p>
            <p className="mb-2 font-medium text-foreground text-sm">
              Repository secrets
            </p>
            <div className="mb-4 overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b text-left">
                    <th className="pb-2 pr-4 font-medium">Secret</th>
                    <th className="pb-2 pr-4 font-medium">Required</th>
                    <th className="pb-2 font-medium">Description</th>
                  </tr>
                </thead>
                <tbody className="text-muted-foreground">
                  <tr className="border-b">
                    <td className="py-2 pr-4">
                      <code className="rounded bg-muted px-1.5 py-0.5">
                        AWS_DEPLOY_ROLE_ARN
                      </code>
                    </td>
                    <td className="py-2 pr-4 text-foreground">Always</td>
                    <td className="py-2">
                      ARN of the GitHub deploy role from step 2
                    </td>
                  </tr>
                  <tr className="border-b">
                    <td className="py-2 pr-4">
                      <code className="rounded bg-muted px-1.5 py-0.5">
                        DATABASE_URL
                      </code>
                    </td>
                    <td className="py-2 pr-4">First deploy only</td>
                    <td className="py-2">
                      Postgres connection string — not needed for upgrades
                    </td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">
                      <code className="rounded bg-muted px-1.5 py-0.5">
                        WRAPS_LICENSE_KEY
                      </code>
                    </td>
                    <td className="py-2 pr-4">First deploy only</td>
                    <td className="py-2">
                      Your Wraps enterprise license key
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="mb-2 font-medium text-foreground text-sm">
              Repository variables (not secrets)
            </p>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b text-left">
                    <th className="pb-2 pr-4 font-medium">Variable</th>
                    <th className="pb-2 pr-4 font-medium">Default</th>
                    <th className="pb-2 font-medium">Description</th>
                  </tr>
                </thead>
                <tbody className="text-muted-foreground">
                  <tr>
                    <td className="py-2 pr-4">
                      <code className="rounded bg-muted px-1.5 py-0.5">
                        AWS_REGION
                      </code>
                    </td>
                    <td className="py-2 pr-4">
                      <code className="rounded bg-muted px-1.5 py-0.5">
                        us-east-1
                      </code>
                    </td>
                    <td className="py-2">AWS region for deployments</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Actions setup 4 — Create a production environment (optional)
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-muted-foreground text-sm">
              Go to{" "}
              <span className="font-medium text-foreground">
                Settings → Environments → New environment
              </span>{" "}
              and create one named{" "}
              <code className="rounded bg-muted px-1.5 py-0.5">production</code>
              . Enable{" "}
              <span className="font-medium text-foreground">
                Required reviewers
              </span>{" "}
              and add yourself — this adds a manual approval step before any
              deploy job runs, giving you a second confirmation gate even after
              you click "Run workflow".
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="text-base">
              Actions setup 5 — How the workflows run
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <ol className="space-y-3 text-muted-foreground text-sm">
              <li className="flex gap-3">
                <span className="font-bold text-foreground shrink-0">1.</span>
                <span>
                  Every Monday, <strong className="text-foreground">Sync from upstream</strong> opens a PR with
                  the latest commits from{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5">
                    wraps-team/wraps
                  </code>
                  . Review the changes and merge when you are ready.
                </span>
              </li>
              <li className="flex gap-3">
                <span className="font-bold text-foreground shrink-0">2.</span>
                <span>
                  After merging, go to{" "}
                  <span className="font-medium text-foreground">
                    Actions → Deploy self-hosted → Run workflow
                  </span>
                  . Select{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5">upgrade</code>{" "}
                  (or{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5">deploy</code>{" "}
                  for a first-time setup) and click Run.
                </span>
              </li>
              <li className="flex gap-3">
                <span className="font-bold text-foreground shrink-0">3.</span>
                <span>
                  If you configured a{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5">
                    production
                  </code>{" "}
                  environment with required reviewers, approve the pending
                  deployment. The job then assumes the OIDC role, runs SST
                  deploy, and applies any pending migrations.
                </span>
              </li>
              <li className="flex gap-3">
                <span className="font-bold text-foreground shrink-0">4.</span>
                <span>
                  Trigger a redeploy of your Vercel project to pick up any
                  dashboard changes.
                </span>
              </li>
            </ol>
          </CardContent>
        </Card>
      </section>

      {/* .env.selfhost Reference */}
      <section className="mb-12">
        <h2 className="mb-4 font-bold text-2xl">.env.selfhost Reference</h2>
        <p className="mb-6 text-muted-foreground">
          The deploy script creates and maintains{" "}
          <code className="rounded bg-muted px-1.5 py-0.5">.env.selfhost</code>{" "}
          in your repo root. These values are read by SST at deploy time and
          injected as Lambda environment variables.
        </p>
        <div className="overflow-x-auto rounded-lg border">
          <table className="w-full text-sm">
            <thead className="bg-muted/50">
              <tr className="border-b text-left">
                <th className="p-3 pr-4 font-medium">Variable</th>
                <th className="p-3 pr-4 font-medium">Required</th>
                <th className="p-3 font-medium">Description</th>
              </tr>
            </thead>
            <tbody className="divide-y text-muted-foreground">
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    DATABASE_URL
                  </code>
                </td>
                <td className="p-3 pr-4 align-top text-foreground">Yes</td>
                <td className="p-3 align-top">
                  Postgres connection string for the control plane database
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    LICENSE_KEY
                  </code>
                </td>
                <td className="p-3 pr-4 align-top text-foreground">Yes</td>
                <td className="p-3 align-top">
                  Your Wraps enterprise license key (
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    wraps_lic_...
                  </code>
                  )
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    BETTER_AUTH_SECRET
                  </code>
                </td>
                <td className="p-3 pr-4 align-top text-foreground">Yes</td>
                <td className="p-3 align-top">
                  Secret for session signing — auto-generated on first deploy,
                  do not rotate without invalidating all active sessions
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    UNSUBSCRIBE_SECRET
                  </code>
                </td>
                <td className="p-3 pr-4 align-top text-foreground">Yes</td>
                <td className="p-3 align-top">
                  HMAC secret used to sign unsubscribe links in outbound emails
                  — auto-generated on first deploy
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    NEXT_PUBLIC_APP_URL
                  </code>
                </td>
                <td className="p-3 pr-4 align-top text-foreground">Yes</td>
                <td className="p-3 align-top">
                  Full URL of your Vercel dashboard deployment (e.g.{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    https://dashboard.yourdomain.com
                  </code>
                  ) — used for CORS and auth redirects
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    WRAPS_API_URL
                  </code>
                </td>
                <td className="p-3 pr-4 align-top text-foreground">Yes</td>
                <td className="p-3 align-top">
                  Lambda function URL — set automatically after first deploy
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    BETTER_AUTH_URL
                  </code>
                </td>
                <td className="p-3 pr-4 align-top text-foreground">Yes</td>
                <td className="p-3 align-top">
                  Same as{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    NEXT_PUBLIC_APP_URL
                  </code>{" "}
                  — set automatically after first deploy
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    SELFHOST_WEB_DOMAIN
                  </code>
                </td>
                <td className="p-3 pr-4 align-top">Optional</td>
                <td className="p-3 align-top">
                  Custom domain for the dashboard — sets{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    AUTH_EMAIL_FROM
                  </code>{" "}
                  to{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    noreply@yourdomain.com
                  </code>{" "}
                  automatically. Pass via{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    --web-domain
                  </code>{" "}
                  flag
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    WRAPS_EMAIL_ROLE_ARN
                  </code>
                </td>
                <td className="p-3 pr-4 align-top">Optional</td>
                <td className="p-3 align-top">
                  IAM role ARN for SES sending — populated automatically when
                  email infrastructure is present
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    AUTH_EMAIL_FROM
                  </code>
                </td>
                <td className="p-3 pr-4 align-top">Optional</td>
                <td className="p-3 align-top">
                  From address for transactional auth emails (password reset,
                  magic links). Must be a verified SES sender
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    AUTH_EMAIL_CONFIGURATION_SET
                  </code>
                </td>
                <td className="p-3 pr-4 align-top">Optional</td>
                <td className="p-3 align-top">
                  SES configuration set name for auth emails — populated
                  automatically when email infrastructure is present
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    AI_GATEWAY_API_KEY
                  </code>
                </td>
                <td className="p-3 pr-4 align-top">Optional</td>
                <td className="p-3 align-top">
                  API key for the AI gateway — enables the AI email template
                  generation feature. Pass via{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    --ai-gateway-api-key
                  </code>{" "}
                  flag
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    ANTHROPIC_API_KEY
                  </code>
                </td>
                <td className="p-3 pr-4 align-top">Optional</td>
                <td className="p-3 align-top">
                  Anthropic API key — alternative to{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    AI_GATEWAY_API_KEY
                  </code>{" "}
                  for direct Anthropic access without a gateway
                </td>
              </tr>
              <tr>
                <td className="p-3 pr-4 align-top">
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    AI_MODEL
                  </code>
                </td>
                <td className="p-3 pr-4 align-top">Optional</td>
                <td className="p-3 align-top">
                  Override the default Claude model used for AI features (e.g.{" "}
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                    claude-sonnet-4-6
                  </code>
                  )
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* Next Steps */}
      <section className="mb-12">
        <h2 className="mb-4 font-bold text-2xl">Next Steps</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          <Card>
            <CardContent className="p-6">
              <Key className="mb-3 h-5 w-5 text-primary" />
              <h3 className="mb-2 font-medium">Verify your domain</h3>
              <p className="mb-3 text-muted-foreground text-sm">
                Add DKIM, SPF, and DMARC records to start sending from your own
                domain.
              </p>
              <Button asChild size="sm" variant="outline">
                <Link href="/docs/guides/domain-verification">
                  Domain verification →
                </Link>
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6">
              <Shield className="mb-3 h-5 w-5 text-primary" />
              <h3 className="mb-2 font-medium">Request production access</h3>
              <p className="mb-3 text-muted-foreground text-sm">
                SES starts in sandbox mode. Request production access to send to
                any recipient.
              </p>
              <Button asChild size="sm" variant="outline">
                <Link href="/docs/guides/production-access">
                  Production access →
                </Link>
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6">
              <Zap className="mb-3 h-5 w-5 text-primary" />
              <h3 className="mb-2 font-medium">Enable AI features</h3>
              <p className="mb-3 text-muted-foreground text-sm">
                Add{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">
                  AI_GATEWAY_API_KEY
                </code>{" "}
                to your{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">
                  .env.selfhost
                </code>{" "}
                and run{" "}
                <code className="rounded bg-muted px-1.5 py-0.5">
                  pnpm selfhost:upgrade
                </code>{" "}
                to enable AI-powered email template generation.
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6">
              <GitFork className="mb-3 h-5 w-5 text-primary" />
              <h3 className="mb-2 font-medium">Tear down</h3>
              <p className="mb-3 text-muted-foreground text-sm">
                Remove all provisioned AWS infrastructure in one command. All
                Lambda functions, S3 buckets, and SST resources are removed.
              </p>
              <code className="rounded bg-muted px-1.5 py-0.5 text-sm">
                pnpm selfhost:destroy
              </code>
            </CardContent>
          </Card>
        </div>
      </section>
    </DocsLayout>
  );
}
