import { globSync } from "node:fs";
import { join } from "node:path";
import type { MetadataRoute } from "next";
import { releases } from "@/app/changelog/releases";
import { PAGE_DATES } from "@/config/page-dates";
import { staticPageRoutes } from "@/lib/page-dates";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://wraps.dev";
  const appDir = join(process.cwd(), "src/app");

  const routes = staticPageRoutes(
    globSync("**/page.tsx", { cwd: appDir })
  ).filter((path) => path !== "/sitemap");

  const pages: MetadataRoute.Sitemap = routes.map((path) => ({
    url: `${baseUrl}${path === "/" ? "" : path}`,
    // Committed in src/config/page-dates.ts, regenerated by `pnpm sitemap:dates`.
    // Neither of the obvious alternatives survives contact with the deploy: file
    // mtime is the git-checkout time on Vercel (all 138 URLs shared one
    // timestamp, so every deploy claimed the whole site had changed), and
    // `git log` during the build sees only Vercel's shallow clone. A route with
    // no recorded date sends no <lastmod> rather than a wrong one.
    lastModified: dateFor(path),
    changeFrequency: path === "/" ? "daily" : "weekly",
    priority:
      path === "/"
        ? 1
        : path.startsWith("/tools")
          ? 0.9
          : path.startsWith("/docs") ||
              path.startsWith("/compare") ||
              path.startsWith("/alternatives")
            ? 0.8
            : 0.7,
  }));

  // Changelog entries are a dynamic route, so the glob above cannot see them.
  // They do not use PAGE_DATES either: all 63 share one template and one data
  // module, so git would give every entry the same committer date — the exact
  // bug the manifest replaced. Each entry's own date is its lastmod.
  const entries: MetadataRoute.Sitemap = releases.map((release) => ({
    url: `${baseUrl}/changelog/${release.slug}`,
    lastModified: new Date(`${release.date}T00:00:00Z`),
    changeFrequency: "yearly",
    priority: 0.5,
  }));

  return [...pages, ...entries];
}

function dateFor(path: string): Date | undefined {
  const recorded = PAGE_DATES[path];
  return recorded === undefined ? undefined : new Date(recorded);
}
